name: 'Chromatic'
permissions:
  contents: read

on:
  push:
    branches-ignore:
      - renovate/*
      - stable-*

jobs:
  pathcheck:
    name: Check for relevant changes
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      changed: ${{ steps.filter.outputs.src }}
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: filter
        with:
          filters: |
            src:
              - 'package.json'
              - 'yarn.lock'
              - '**/*.js'
              - '**/*.jsx'
              - '**/*.ts'
              - '**/*.tsx'
              - '**/*.css'
              - '**/*.scss'
              - '.github/workflows/chromatic.yml'

  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: pathcheck
    if: github.repository == 'mastodon/mastodon' && needs.pathcheck.outputs.changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Javascript environment
        uses: ./.github/actions/setup-javascript

      - name: Build Storybook
        run: yarn build-storybook

      - name: Run Chromatic
        uses: chromaui/action@c93e0bc3a63aa176e14a75b61a31847cbfdd341c # v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          zip: true
          storybookBuildDir: 'storybook-static'
          exitOnceUploaded: true # Exit immediately after upload
          autoAcceptChanges: 'main' # Auto-accept changes on main branch only
